name: 'Deploy Terraform to AWS DEV'

on:
  push:
    branches:
      - dev

 
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'eu-central-1'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: cd ./dev/ && terraform init
    
    - name: Terraform Format
      run: cd ./dev/ &&  terraform validate

    - name: Terraform Plan
      run: cd ./dev/ &&  terraform plan

    - name: Terraform Apply
      run: cd ./dev/ &&  terraform apply
